From:
https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html


Environment was created with:
conda create --name  Nystromformer python=3.7
conda install -n Nystromformer pip
conda activate Nystromformer

!pip install torch==1.7.1
!pip install torchvision==0.8.2


In [17]:
import torch
import numpy as np

In [18]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [19]:
# from numpy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [20]:
x_np

tensor([[1, 2],
        [3, 4]])

In [21]:
# from another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4379, 0.3335],
        [0.1629, 0.5807]]) 



In [22]:
#shape
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7492, 0.0650, 0.3049],
        [0.9043, 0.7244, 0.4119]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [23]:
# Tensor attributes

tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [24]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

tensor

tensor([[0.3791, 0.6023, 0.4230, 0.4251],
        [0.3014, 0.8433, 0.7345, 0.7682],
        [0.4361, 0.9318, 0.9461, 0.8927]])

# Operators

In [25]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")


tensor.mul(tensor) 
 tensor([[0.1437, 0.3628, 0.1789, 0.1807],
        [0.0908, 0.7111, 0.5394, 0.5901],
        [0.1902, 0.8682, 0.8951, 0.7969]]) 

tensor * tensor 
 tensor([[0.1437, 0.3628, 0.1789, 0.1807],
        [0.0908, 0.7111, 0.5394, 0.5901],
        [0.1902, 0.8682, 0.8951, 0.7969]])


In [26]:
# inplace operators have a suffix _
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[0.3791, 0.6023, 0.4230, 0.4251],
        [0.3014, 0.8433, 0.7345, 0.7682],
        [0.4361, 0.9318, 0.9461, 0.8927]]) 

tensor([[5.3791, 5.6023, 5.4230, 5.4251],
        [5.3014, 5.8433, 5.7345, 5.7682],
        [5.4361, 5.9318, 5.9461, 5.8927]])


# A Gentle Introduction to torch.autograd

In [27]:
# !conda remove pytorch torchvision -y
# !pip uninstall torch -y
# !pip uninstall torch -y  # yes twice
# !pip3 uninstall -y torch torchvision
# !pip3 uninstall -y torch torchvision
# !pip uninstall -y torch torchvision
# !pip uninstall -y torch torchvision

In [29]:
# !pip install torch==1.7.1

In [30]:
# !pip install torchvision==0.8.2


In [31]:
#Let’s take a look at a single training step. For this example, we load a pretrained resnet18 model from torchvision. We create a random data tensor to represent a single image with 3 channels, and height & width of 64, and its corresponding label initialized to some random values.

import torch
import torchvision

model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)



In [32]:
labels

tensor([[8.0098e-02, 4.4756e-01, 4.5881e-01, 5.4276e-02, 5.4434e-01, 5.2426e-01,
         4.4787e-02, 1.6680e-02, 1.9464e-01, 4.4486e-01, 8.2914e-01, 6.7444e-01,
         8.4176e-01, 1.3151e-01, 6.5901e-02, 1.6886e-01, 5.3271e-01, 3.2581e-01,
         2.4316e-01, 5.7487e-01, 1.0449e-01, 5.5043e-01, 2.8974e-01, 1.5953e-01,
         7.8492e-01, 8.3033e-01, 6.8157e-01, 9.0992e-01, 4.6673e-01, 7.8064e-01,
         1.4195e-02, 2.4048e-01, 8.3334e-01, 5.9467e-01, 2.2144e-01, 8.1356e-01,
         7.4459e-01, 3.6248e-01, 5.1022e-01, 1.4615e-01, 3.7762e-01, 3.5555e-01,
         2.6241e-01, 4.7632e-01, 3.8910e-01, 4.6211e-01, 7.1702e-01, 2.0004e-01,
         7.2053e-01, 5.1364e-01, 6.7404e-01, 7.1665e-01, 5.2356e-01, 8.7721e-01,
         3.5720e-01, 3.9345e-01, 9.3270e-01, 5.2297e-01, 8.8642e-01, 7.1024e-01,
         7.4385e-01, 1.1979e-01, 2.6973e-01, 1.9735e-02, 1.3584e-01, 4.8917e-01,
         3.6572e-01, 7.3799e-01, 7.4818e-02, 5.1560e-01, 3.9652e-01, 5.8992e-01,
         3.3390e-01, 9.3320e

In [33]:
prediction = model(data) # forward pass

In [36]:
prediction.shape

torch.Size([1, 1000])

In [37]:
loss = (prediction - labels).sum()

In [39]:
loss

tensor(-498.7801, grad_fn=<SumBackward0>)

In [40]:
loss.backward() # backward pass

In [41]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [42]:
optim.step() #gradient descent

# Neural Networks

In [46]:
# https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html

In [44]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [45]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
